<?php

namespace App\Services;

use App\Models\BoardSettlement;
use App\Models\BoardTransaction;

/**
 * BoardLedgerService
 *
 * Responsible for synchronising a BoardSettlement record into the
 * board_transactions ledger.
 *
 * Design:
 *  A single settlement for a given date produces UP TO TWO ledger rows:
 *
 *   1. "get_tickets"  — ticket stock received (adds to balance).
 *      Created when total_ticket_value > 0.
 *
 *   2. "paid_bill"    — winning + cash + bank paid to board (reduces balance).
 *      Created when any payment field > 0.
 *
 *  Both rows are keyed on (board_settlement_id, description) so that
 *  re-saving the same settlement merely updates — never duplicates — the
 *  ledger rows. After posting, all running balances are recalculated.
 */
class BoardLedgerService
{
    // ── Public API ─────────────────────────────────────────────────────────────

    /**
     * Post (or refresh) the two ledger rows for a settlement.
     * Safe to call on both create and update.
     */
    public function postSettlement(BoardSettlement $settlement): void
    {
        $this->upsertGetTickets($settlement);
        $this->upsertPaidBill($settlement);
        BoardTransaction::recalculateBalances();
    }

    /**
     * Remove all ledger rows that were generated by this settlement,
     * then rebuild the running balances.
     */
    public function retractSettlement(BoardSettlement $settlement): void
    {
        BoardTransaction::where('board_settlement_id', $settlement->id)->delete();
        BoardTransaction::recalculateBalances();
    }

    // ── Private helpers ────────────────────────────────────────────────────────

    /**
     * Upsert the "get_tickets" ledger row.
     * Only created when the settlement has a non-zero ticket value.
     */
    private function upsertGetTickets(BoardSettlement $settlement): void
    {
        $value = (float) $settlement->total_ticket_value;

        if ($value <= 0) {
            // If the ticket value was cleared on a re-save, remove any existing row.
            BoardTransaction::where('board_settlement_id', $settlement->id)
                ->where('description', 'get_tickets')
                ->delete();
            return;
        }

        BoardTransaction::updateOrCreate(
            [
                'board_settlement_id' => $settlement->id,
                'description'         => 'get_tickets',
            ],
            [
                'date'       => $settlement->date,
                'ticket_qty' => $settlement->total_tickets_received ?? 0,
                'ticket_value' => $value,
                // Winning / cash irrelevant for this row type
                'winning_amount' => 0,
                'nlb_winning'    => 0,
                'dlb_winning'    => 0,
                'cash_amount'    => 0,
                'bank_deposits'  => 0,
                'nlb_tiers'      => null,
                'dlb_tiers'      => null,
                'cash_denoms'    => null,
                'credit_amount'  => 0,
                'cr_amount'      => $value,   // +ticket_value → increases balance
                'notes'          => 'Auto-posted from Board Settlement',
            ]
        );
    }

    /**
     * Upsert the "paid_bill" ledger row.
     * Only created when at least one payment field is non-zero.
     */
    private function upsertPaidBill(BoardSettlement $settlement): void
    {
        $winning = (float) $settlement->total_winning;
        $cash    = (float) $settlement->cash_total;
        $bank    = (float) $settlement->bank_deposits;
        $total   = $winning + $cash + $bank;

        if ($total <= 0) {
            BoardTransaction::where('board_settlement_id', $settlement->id)
                ->where('description', 'paid_bill')
                ->delete();
            return;
        }

        // Build compact JSON breakdowns (only non-zero denominations)
        $nlbTiers   = $this->compactTiers($settlement, BoardSettlement::NLB_TIERS);
        $dlbTiers   = $this->compactTiers($settlement, BoardSettlement::DLB_TIERS);
        $cashDenoms = $this->compactTiers($settlement, BoardSettlement::CASH_DENOMS);

        BoardTransaction::updateOrCreate(
            [
                'board_settlement_id' => $settlement->id,
                'description'         => 'paid_bill',
            ],
            [
                'date'           => $settlement->date,
                'ticket_qty'     => null,
                'ticket_value'   => 0,
                'winning_amount' => $winning,
                'nlb_winning'    => (float) $settlement->nlb_total,
                'dlb_winning'    => (float) $settlement->dlb_total,
                'cash_amount'    => $cash,
                'bank_deposits'  => $bank,
                'nlb_tiers'      => $nlbTiers,
                'dlb_tiers'      => $dlbTiers,
                'cash_denoms'    => $cashDenoms,
                'credit_amount'  => 0,
                'cr_amount'      => -$total,  // −(winning+cash+bank) → reduces balance
                'notes'          => 'Auto-posted from Board Settlement',
            ]
        );
    }

    /**
     * Extract non-zero tier values from the settlement into a compact array.
     * E.g. ['nlb_40' => 5, 'nlb_1000' => 2]
     */
    private function compactTiers(BoardSettlement $settlement, array $tierMap): array
    {
        $result = [];
        foreach (array_keys($tierMap) as $col) {
            $qty = (int) ($settlement->{$col} ?? 0);
            if ($qty > 0) {
                $result[$col] = $qty;
            }
        }
        return $result;
    }
}
